// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsPW0vHdDh_P9yxIacAfmFYNrYXdbCAgU',
    appId: '1:478998143094:web:d139566edcdf13511a3f57',
    messagingSenderId: '478998143094',
    projectId: 'tesoapp-be9bc',
    authDomain: 'tesoapp-be9bc.firebaseapp.com',
    storageBucket: 'tesoapp-be9bc.firebasestorage.app',
    measurementId: 'G-VWPSHT2Y08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC61hZ_LigPXQdPVdwqV0GSIqdcLGJbtDY',
    appId: '1:478998143094:android:dd4d8699480f0d801a3f57',
    messagingSenderId: '478998143094',
    projectId: 'tesoapp-be9bc',
    storageBucket: 'tesoapp-be9bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApB_bMyCkyCAKR-XgJRNWhT2f3omfdRdU',
    appId: '1:478998143094:ios:086ed17ba1e195011a3f57',
    messagingSenderId: '478998143094',
    projectId: 'tesoapp-be9bc',
    storageBucket: 'tesoapp-be9bc.firebasestorage.app',
    androidClientId: '478998143094-bjjrphhkqtch8f8r6j9nl0h0cle6e3o7.apps.googleusercontent.com',
    iosClientId: '478998143094-p4jnuha0c3fikj20u2f3vpfo5jd5c6u5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApB_bMyCkyCAKR-XgJRNWhT2f3omfdRdU',
    appId: '1:478998143094:ios:086ed17ba1e195011a3f57',
    messagingSenderId: '478998143094',
    projectId: 'tesoapp-be9bc',
    storageBucket: 'tesoapp-be9bc.firebasestorage.app',
    androidClientId: '478998143094-bjjrphhkqtch8f8r6j9nl0h0cle6e3o7.apps.googleusercontent.com',
    iosClientId: '478998143094-p4jnuha0c3fikj20u2f3vpfo5jd5c6u5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsPW0vHdDh_P9yxIacAfmFYNrYXdbCAgU',
    appId: '1:478998143094:web:1fefa8c2e1915d2e1a3f57',
    messagingSenderId: '478998143094',
    projectId: 'tesoapp-be9bc',
    authDomain: 'tesoapp-be9bc.firebaseapp.com',
    storageBucket: 'tesoapp-be9bc.firebasestorage.app',
    measurementId: 'G-HPLQ0LN7Z3',
  );

}